Repository aivivn/Machine-Learning-Yearning-Vietnamese-Translation, pull requests merged in 2019-11, with the labels that each got.

#169 add chapter 19
  chapters/ch19.md
  glossary.md
Labels: first round, high priority

#175 Dịch chương 23
  chapters/ch23.md
Labels: high priority, review wanted

#192 add chapter 24
  chapters/ch24.md
Labels: high priority, review wanted

#195 Dịch chương 25
  chapters/ch25.md
Labels: high priority, review wanted

#193 Dịch chương 26
  chapters/ch26.md
Labels: high priority, review wanted

#234 Dịch chương 28
  chapters/ch28.md
Labels: high priority, review wanted

#225 Dịch chương 29
  chapters/ch29.md
Labels: high priority, review wanted

#228 Dịch Chương 30
  chapters/ch30.md
Labels: high priority, review wanted

#262 Update ch06.md
  chapters/ch06.md
Labels: high priority, review wanted

#251 Dịch chương 32
  chapters/ch32.md
Labels: high priority, review wanted

#247 Dịch chương 33
  chapters/ch33.md
Labels: high priority

#256 Thêm "domain adaptation" và "multitask learning" vào glossary.md
  glossary.md
Labels: high priority

#254 Dịch chương 34
  chapters/ch34.md
Labels: high priority, review wanted

#273 Dịch chương 36
  chapters/ch36.md
Labels: high priority

#276 Dịch chương 35
  chapters/ch35.md
Labels: high priority

#279 Dịch chương 37
  chapters/ch37.md
Labels: high priority

#302 Dịch chương 38
  chapters/ch38.md
Labels: high priority, review wanted

#282 Dịch chương 40
  chapters/ch40.md
Labels: high priority

#305 Thêm data mismatch và training dev set vào glossary
  chapters/all_chapters.md
  chapters/all_chapters_vietnames_only.md
  chapters/ch40.md
  glossary.md
Labels: high priority

#298 Dịch chương 42
  chapters/ch42.md
Labels: high priority

#278 Dịch chương 41
  chapters/ch41.md
Labels: high priority

#296 Dịch chương 43
  chapters/ch43.md
Labels: high priority

#329 Dịch chương 46
  chapters/ch46.md
Labels: high priority

#304 Dịch chương 45
  chapters/ch45.md
Labels: high priority

#340 Dịch chương 49
  chapters/ch49.md
Labels: high priority

#342 Dịch chương 50
  chapters/ch50.md
Labels: high priority

#360 Dịch chương 48
  chapters/ch48.md
Labels: high priority

#349 Dịch chương 51
  chapters/ch51.md
Labels: high priority

#355 Dịch chương 53
  chapters/ch53.md
Labels: high priority

#363 Dịch Chương 52
  chapters/ch52.md
Labels: high priority

#364 Dịch chương 55
  chapters/ch55.md
Labels: high priority

#362 Dịch chương 56
  chapters/ch56.md
Labels: high priority
