Repository aivivn/Machine-Learning-Yearning-Vietnamese-Translation, pull requests merged in 2019-10, with the labels that each got.

#19 add instruction to glossary.md
  README.md
  glossary.md
Labels: documentation

#24 add original copy and format of chapter 1
  chapters/ch01.md
  imgs/C01_01.png
Labels: original copy

#41 update glossary chap 1
  glossary.md
Labels: glossary

#40 Update dịch chap 1
  chapters/ch01.md
Labels: translation

#54 Dịch chương 2
  chapters/ch02.md
Labels: high priority, review wanted, translation

#81 Glossary chap 1 -14
  glossary.md
Labels: high priority, review wanted

#87 Update glossary.md
  glossary.md
Labels: high priority

#83 Dịch chap 04
  chapters/ch04.md
Labels: high priority, review wanted

#132 cross validation -> kiểm định chéo
  glossary.md
Labels: glossary, high priority, review wanted

#126 Cập nhật một vài từ dễ vào bảng thuật ngữ
  glossary.md
Labels: glossary, high priority, review wanted

#91 Dịch chap 06
  chapters/ch06.md
Labels: high priority, review wanted

#70 Translate chap 07
  chapters/ch07.md
Labels: high priority, review wanted

#125 add bias and variance to glossary
  glossary.md
Labels: glossary, high priority, review wanted

#97 Dịch Chương 8
  chapters/ch08.md
Labels: first round, high priority, review wanted

#77 Dich chuong 9
  chapters/ch09.md
Labels: first round, high priority, review wanted

#140 Dịch chương 14
  chapters/ch14.md
Labels: first round, review wanted

#143 Chỉnh sửa chương 1
  chapters/ch01.md
Labels: second round

#117 Dịch chương 10
  chapters/ch10.md
Labels: first round, high priority, review wanted

#150 Dịch chương 11
  chapters/ch11.md
Labels: first round, high priority, review wanted

#160 Dịch chương 13
  chapters/ch13.md
Labels: first round, high priority, review wanted

#162 Thêm glossary black box/ eyeball dev set
  glossary.md
Labels: high priority

#159 Chỉnh sửa chương 4
  chapters/all_chapters.md
  chapters/ch04.md
Labels: second round

#161 Dịch chương 15
  chapters/ch15.md
Labels: first round, high priority, review wanted

#164 Dịch chương 16
  chapters/ch16.md
Labels: high priority, review wanted, translation

#168 Dịch Chương 17
  chapters/ch17.md
Labels: high priority, review wanted

#156 Dịch chương 18
  chapters/ch18.md
  glossary.md
Labels: first round, high priority, review wanted, translation

#172 Dịch chương 20
  chapters/ch20.md
Labels: high priority, review wanted

#181 Dịch ch22.md
  chapters/ch22.md
Labels: high priority, review wanted
